---
- hosts: target1
  gather_facts: False
  tasks:
    - name: "{{ item.name }}"
      wait_for:
        host: "{{ item.destination }}"
        port: "{{ item.port }}"
        state: started
        delay: 0
        timeout: 1
      loop:
        - {name: 'teste1', destination: '10.0.0.146', port: '22'}
        - {name: 'teste2', destination: '10.0.0.146', port: '8544'}

~                                                                      
